name: deploy on push
on: [push]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER_NAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            sudo mkdir -p /var/www/html
            sudo cp -r html/* /var/www/html/